[program:sync]   
command=python /home/pi/sync/server.py                           
directory=/home/pi/sync 
environment=HOME='/home/pi'
user=pi          
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/sync-access.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stdout_capture_maxbytes=1MB
stderr_logfile=/var/log/supervisor/sync-error.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
stderr_capture_maxbytes=1MB